[package]
name = "oxid-adapter-storage-memory"
description = "In-memory wallet persistence adapter for Oxid development and tests"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
oxid-credential-application.workspace = true
oxid-credential-domain.workspace = true
oxid-identity-application.workspace = true
oxid-identity-domain.workspace = true
oxid-foundation.workspace = true
oxid-wallet-application.workspace = true
oxid-wallet-domain.workspace = true

[lints]
workspace = true
