#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
# Receipt-bound, state-preserving Android Portal manual phases.
set -euo pipefail
readonly ROOT="$(cd -- "${BASH_SOURCE[0]%/*}/.." && pwd -P)"
readonly STATE="${OXID_PORTAL_PHASE_STATE_DIR:-$ROOT/target/portal-tailnet-manual/phases}"
readonly OPERATION="${1:-}"
readonly CONFIGURE_RECEIPT="$STATE/configure-receipt.json"
readonly BUILD_RECEIPT="$STATE/build-receipt.json"
readonly ADMIT_RECEIPT="$STATE/admit-receipt.json"
readonly INSTALL_RECEIPT="$STATE/install-receipt.json"
readonly LAUNCH_RECEIPT="$STATE/launch-receipt.json"
readonly APK="$ROOT/target/dx/oxid-app/debug/android/app/app/build/outputs/apk/debug/app-debug.apk"
readonly ARTIFACT_RECEIPT="$ROOT/target/dx/oxid-app/debug/android/oxid-app-artifact-receipt.json"
readonly PACKAGE="io.medianox.oxid"
fail() { printf 'portal-tailnet-manual-phases: FAIL phase=%s\n' "$1" >&2; exit 1; }
case "$OPERATION" in configure|build|admit|install|launch|status) ;; *) fail usage ;; esac
for command_name in git jq shasum; do command -v "$command_name" >/dev/null 2>&1 || fail missing-tool; done
umask 077; mkdir -p "$STATE"; chmod 700 "$STATE"; [ -d "$STATE" ] && [ ! -L "$STATE" ] || fail state
head="$(git -C "$ROOT" rev-parse HEAD)"; tree="$(git -C "$ROOT" rev-parse 'HEAD^{tree}')"
sha() { shasum -a 256 "$1" | awk '{print $1}'; }
private_file() { [ -f "$1" ] && [ ! -L "$1" ] && [ "$(stat -f '%Lp' "$1" 2>/dev/null || stat -c '%a' "$1")" = 600 ]; }
write_receipt() { local out="$1" value="$2" tmp; tmp="$(mktemp "$STATE/.receipt.XXXXXX")"; printf '%s\n' "$value" >"$tmp"; chmod 600 "$tmp"; mv "$tmp" "$out"; }
manifest_valid() { local p="$1"; [[ "$p" = /* ]] && [ -f "$p" ] && [ ! -L "$p" ] && jq -e '.schema == "oxid-portal-deployment-v3" and (.issuerOrigin|type == "string") and (.issuerDid|type == "string") and (.issuerMethod|type == "string") and (.issuerJubjubJwkSha256|test("^[0-9a-f]{64}$")) and (tostring|test("(?i)(token|secret|capability|privateKey|wallet_seed)")|not)' "$p" >/dev/null; }
config_valid() { private_file "$CONFIGURE_RECEIPT" && jq -e --arg h "$head" --arg t "$tree" '.schema == "oxid-portal-manual-configure-v1" and .source == {head:$h,tree:$t} and .profile == "tailnet-android" and (.manifest.path|type == "string") and (.manifest.sha256|test("^[0-9a-f]{64}$"))' "$CONFIGURE_RECEIPT" >/dev/null && manifest_valid "$(jq -r '.manifest.path' "$CONFIGURE_RECEIPT")" && [ "$(sha "$(jq -r '.manifest.path' "$CONFIGURE_RECEIPT")")" = "$(jq -r '.manifest.sha256' "$CONFIGURE_RECEIPT")" ]; }
artifact_valid() { [ -f "$APK" ] && [ -f "$ARTIFACT_RECEIPT" ] && jq -e --arg h "$head" --arg t "$tree" --arg apk "$APK" --arg digest "$(sha "$APK")" '.schema == "oxid-app-artifact-receipt-v1" and .head == $h and .tree == $t and .platform == "android" and .artifact == $apk and .artifactSha256 == $digest and (.configuration|type == "string") and (.target|type == "string")' "$ARTIFACT_RECEIPT" >/dev/null; }
build_valid() { private_file "$BUILD_RECEIPT" && config_valid && artifact_valid && jq -e --arg h "$head" --arg t "$tree" --arg c "$(sha "$CONFIGURE_RECEIPT")" --arg apk "$(sha "$APK")" --arg cfg "$(jq -r '.configuration' "$ARTIFACT_RECEIPT")" --arg target "$(jq -r '.target' "$ARTIFACT_RECEIPT")" '.schema == "oxid-portal-manual-build-v1" and .source == {head:$h,tree:$t} and .predecessor.configureSha256 == $c and .artifact == {sha256:$apk,configuration:$cfg,target:$target}' "$BUILD_RECEIPT" >/dev/null; }
admit_valid() { private_file "$ADMIT_RECEIPT" && build_valid && jq -e --arg b "$(sha "$BUILD_RECEIPT")" --arg apk "$(sha "$APK")" '.schema == "oxid-portal-manual-admit-v1" and .predecessor.buildSha256 == $b and .artifactSha256 == $apk and .admission == {signing:"verified",schema:"verified",profile:"verified"}' "$ADMIT_RECEIPT" >/dev/null; }
install_valid() { private_file "$INSTALL_RECEIPT" && admit_valid && jq -e --arg a "$(sha "$ADMIT_RECEIPT")" --arg apk "$(sha "$APK")" '.schema == "oxid-portal-manual-install-v1" and .predecessor.admitSha256 == $a and .artifactSha256 == $apk and .applicationDataCleared == false and (.device.sha256|test("^[0-9a-f]{64}$"))' "$INSTALL_RECEIPT" >/dev/null; }
launch_valid() { private_file "$LAUNCH_RECEIPT" && install_valid && jq -e --arg i "$(sha "$INSTALL_RECEIPT")" --arg apk "$(sha "$APK")" '.schema == "oxid-portal-manual-launch-v1" and .predecessor.installSha256 == $i and .artifactSha256 == $apk and .applicationDataCleared == false and .outcome == "running"' "$LAUNCH_RECEIPT" >/dev/null; }
android_env() { OXID_MOBILE_CUSTODY=development OXID_MOBILE_PORTAL_PROFILE=tailnet-android OXID_BUILD_PORTAL_PUBLIC_ORIGIN="$(jq -r '.manifest.issuerOrigin' "$CONFIGURE_RECEIPT")" OXID_BUILD_PORTAL_DEPLOYMENT_MANIFEST_PATH="$(jq -r '.manifest.path' "$CONFIGURE_RECEIPT")" OXID_BUILD_PORTAL_DEPLOYMENT_MANIFEST_SHA256="$(jq -r '.manifest.sha256' "$CONFIGURE_RECEIPT")" "$ROOT/scripts/run-android-tailnet.sh" "$1"; }
android_sdk="${ANDROID_HOME:-${ANDROID_SDK_ROOT:-}}"; [ -n "$android_sdk" ] || android_sdk="$HOME/Library/Android/sdk"
adb="$android_sdk/platform-tools/adb"
select_device() { [ -x "$adb" ] || fail adb; local devices; devices="$($adb devices | awk 'NR>1 && $2=="device" && $1 !~ /^emulator-/ {print $1}')"; [ "$(awk 'NF{n++} END{print n+0}' <<<"$devices")" -eq 1 ] || fail physical-device; device="$devices"; ANDROID_SERIAL="$device" "$adb" shell getprop ro.kernel.qemu | tr -d '\r\n' | grep -Fx '0' >/dev/null || fail physical-device; }
case "$OPERATION" in
configure) manifest="${OXID_BUILD_PORTAL_DEPLOYMENT_MANIFEST_PATH:-}"; manifest_valid "$manifest" || fail manifest-schema; if config_valid; then exit 0; fi; [ ! -e "$CONFIGURE_RECEIPT" ] || fail stale-configure-receipt; write_receipt "$CONFIGURE_RECEIPT" "$(jq -cn --arg h "$head" --arg t "$tree" --arg p "$manifest" --arg s "$(sha "$manifest")" --arg origin "$(jq -r '.issuerOrigin' "$manifest")" '{schema:"oxid-portal-manual-configure-v1",source:{head:$h,tree:$t},profile:"tailnet-android",manifest:{path:$p,sha256:$s,issuerOrigin:$origin}}')" ;;
build) config_valid || fail configure-receipt; if build_valid; then exit 0; fi; [ ! -e "$BUILD_RECEIPT" ] || fail stale-build-receipt; android_env build; artifact_valid || fail artifact-receipt; write_receipt "$BUILD_RECEIPT" "$(jq -cn --arg h "$head" --arg t "$tree" --arg c "$(sha "$CONFIGURE_RECEIPT")" --arg apk "$(sha "$APK")" --arg cfg "$(jq -r '.configuration' "$ARTIFACT_RECEIPT")" --arg target "$(jq -r '.target' "$ARTIFACT_RECEIPT")" '{schema:"oxid-portal-manual-build-v1",source:{head:$h,tree:$t},predecessor:{configureSha256:$c},artifact:{sha256:$apk,configuration:$cfg,target:$target}}')" ;;
admit) build_valid || fail build-receipt; if admit_valid; then exit 0; fi; [ ! -e "$ADMIT_RECEIPT" ] || fail stale-admit-receipt; apksigner="$android_sdk/build-tools/${OXID_ANDROID_BUILD_TOOLS_VERSION:-35.0.0}/apksigner"; [ -x "$apksigner" ] || fail apksigner; "$apksigner" verify --verbose --print-certs "$APK" >/dev/null || fail signing; artifact_valid || fail artifact-receipt; write_receipt "$ADMIT_RECEIPT" "$(jq -cn --arg b "$(sha "$BUILD_RECEIPT")" --arg apk "$(sha "$APK")" '{schema:"oxid-portal-manual-admit-v1",predecessor:{buildSha256:$b},artifactSha256:$apk,admission:{signing:"verified",schema:"verified",profile:"verified"}}')" ;;
install) admit_valid || fail admit-receipt; if install_valid; then exit 0; fi; [ ! -e "$INSTALL_RECEIPT" ] || fail stale-install-receipt; select_device; ANDROID_SERIAL="$device" "$adb" install -r "$APK" >/dev/null || fail install; write_receipt "$INSTALL_RECEIPT" "$(jq -cn --arg a "$(sha "$ADMIT_RECEIPT")" --arg apk "$(sha "$APK")" --arg d "$(printf %s "$device"|shasum -a 256|awk '{print $1}')" '{schema:"oxid-portal-manual-install-v1",predecessor:{admitSha256:$a},artifactSha256:$apk,device:{sha256:$d},applicationDataCleared:false}')" ;;
launch) install_valid || fail install-receipt; if launch_valid; then exit 0; fi; [ ! -e "$LAUNCH_RECEIPT" ] || fail stale-launch-receipt; select_device; [ "$(printf %s "$device"|shasum -a 256|awk '{print $1}')" = "$(jq -r '.device.sha256' "$INSTALL_RECEIPT")" ] || fail device; ANDROID_SERIAL="$device" "$adb" shell am start -n "$PACKAGE/dev.dioxus.main.MainActivity" >/dev/null || fail launch; write_receipt "$LAUNCH_RECEIPT" "$(jq -cn --arg i "$(sha "$INSTALL_RECEIPT")" --arg apk "$(sha "$APK")" '{schema:"oxid-portal-manual-launch-v1",predecessor:{installSha256:$i},artifactSha256:$apk,outcome:"running",applicationDataCleared:false}')" ;;
status) launch_valid && printf '%s\n' 'portal-tailnet-manual-phases: READY' || fail incomplete ;;
esac
