[package]
name = "oxid-adapter-did-midnight"
description = "Midnight DID resolver adapters for Oxid"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
futures.workspace = true
oxid-identity-application.workspace = true
oxid-identity-domain.workspace = true
reqwest = { workspace = true, features = ["stream"] }
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true

[lints]
workspace = true
